jwt:
  secret: ENC(CISHuXgDturlysHYGlw903jOfTof4nZAGtaLX7kDqVQQMWqyPKRp2hKXds9k0xch+8MRmdYibGlVeqtAhIFZQP119qVJifPaXl5PZ/2TdKuCOqZfwgdXOBPPOR8LQOk30Bj98kcwNTD77TvaPCj4sl7TCcnYbidiyQEQEIwrp6VLNnkljzzpYg0XCSTgYzwFFesGhYSB2vBz2ww1AAJeKeWYO1CBFIsP15pJl/DMUYcJY0xyR4vyMqGOYRnX/FsRyV1uBO6RFWaXL7AbXBfbeSGptZxG68gcUuysIF7+GvKHLEgmGEcVJNv8dpuB2+YuVwRdI83BSLxaXcnrm5VDsY/e8fHrEps3y9IaB60SP2E=)
  expire_in_seconds: 3600

