spring:
  config:
    activate:
      on-profile:
        - local
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: localhost
      host: 9200
      username: elastic
      password: changeme

---
spring:
  config:
    activate:
      on-profile:
        - dev
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: 35.216.61.47
      host: 9200
      username: elastic
      password: changeme

