spring:
  config:
    activate:
      on-profile:
        - local
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: ENC(1rBlgKHg9bb8VBF5n9TWKJIerQLkJ77T)
      username: ENC(o/CleJkct9n0sOnYQUJuUw==)
      password: ENC(La+OE4w/F/pf3Q2cm6LiZ3edL3s/gwcm)

---
spring:
  config:
    activate:
      on-profile:
        - dev
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: ENC(E5lgSEAlUg0eeVBPZdSkFZsu4IDqaNhGsVOi7pGjoaU=)
      username: ENC(o/CleJkct9n0sOnYQUJuUw==)
      password: ENC(La+OE4w/F/pf3Q2cm6LiZ3edL3s/gwcm)

