spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: redis_boot
      port: 6379
---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379